"""Minify + gzip web/* into a PROGMEM asset table.

Runs as a PlatformIO pre-build extra_script and as a plain module under test.
Stdlib only: every environment and any CI must build without pip.
"""
import gzip
import hashlib
import re
from dataclasses import dataclass
from pathlib import Path

CONTENT_TYPES = {
    ".html": "text/html",
    ".css": "text/css",
    ".js": "application/javascript",
    ".svg": "image/svg+xml",
    ".json": "application/json",
    ".ico": "image/x-icon",
}
DEFAULT_CONTENT_TYPE = "application/octet-stream"
ETAG_HEX_CHARS = 16
GZIP_LEVEL = 9
BYTES_PER_LINE = 16
SOURCE_ENCODING = "utf-8"

TEXT_SUFFIXES = (".html", ".css", ".js")

# Only whole-line comments are stripped; a trailing-comment rule cannot tell
# code from the contents of a string literal without a real parser.
FULL_LINE_COMMENT = re.compile(r'^\s*(//|/\*.*\*/\s*$|<!--.*-->\s*$)')


@dataclass(frozen=True)
class Asset:
    path: str
    data: bytes           # gzipped
    content_type: str
    etag: str
    raw_len: int


def content_type_for(suffix: str) -> str:
    return CONTENT_TYPES.get(suffix.lower(), DEFAULT_CONTENT_TYPE)


def etag_for(raw: bytes) -> str:
    return '"%s"' % hashlib.sha256(raw).hexdigest()[:ETAG_HEX_CHARS]


def gzip_bytes(raw: bytes) -> bytes:
    # mtime=0: a header timestamp would change the ETag on every build.
    return gzip.compress(raw, compresslevel=GZIP_LEVEL, mtime=0)


def minify(text: str) -> str:
    kept = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or FULL_LINE_COMMENT.match(stripped):
            continue
        kept.append(stripped)
    # Newline, not "": joining bare would break ASI, merge adjacent HTML
    # words, and flatten template literals. gzip reduces it to near nothing.
    return "\n".join(kept)


def _c_array(data: bytes) -> str:
    lines = []
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i:i + BYTES_PER_LINE]
        lines.append("    " + "".join("0x%02x," % b for b in chunk))
    return "\n".join(lines)


def collect_assets(web_dir: Path) -> list[Asset]:
    web_dir = Path(web_dir)
    if not web_dir.is_dir():
        raise FileNotFoundError("web asset directory not found: %s" % web_dir)
    assets = []
    for path in sorted(web_dir.rglob("*")):
        if not path.is_file():
            continue
        if path.suffix.lower() in TEXT_SUFFIXES:
            raw = minify(path.read_text(encoding=SOURCE_ENCODING)).encode(SOURCE_ENCODING)
        else:
            raw = path.read_bytes()
        assets.append(Asset(
            path="/" + path.relative_to(web_dir).as_posix(),
            data=gzip_bytes(raw),
            content_type=content_type_for(path.suffix),
            etag=etag_for(raw),
            raw_len=len(raw),
        ))
    return assets


def render_header() -> str:
    return """// Generated by scripts/gen_web_assets.py — do not edit.
#ifndef WEB_ASSETS_H
#define WEB_ASSETS_H

#include <stddef.h>
#include <stdint.h>

struct WebAsset {
  const char* path;
  const uint8_t* data;  // gzip-compressed, PROGMEM
  uint32_t len;
  const char* content_type;
  const char* etag;  // quoted, content-hash
};

extern const WebAsset kWebAssets[];
extern const uint32_t kWebAssetCount;

#endif
"""


def render_source(assets: list[Asset]) -> str:
    out = ['// Generated by scripts/gen_web_assets.py — do not edit.',
           '#include "web_assets.h"', '', '#include <pgmspace.h>', '']
    for i, a in enumerate(assets):
        out.append("// %s — %d B raw, %d B gzip" % (a.path, a.raw_len, len(a.data)))
        out.append("static const uint8_t kAsset%d[] PROGMEM = {" % i)
        out.append(_c_array(a.data))
        out.append("};")
        out.append("")
    out.append("const WebAsset kWebAssets[] = {")
    for i, a in enumerate(assets):
        out.append('    {"%s", kAsset%d, %d, "%s", "%s"},'
                   % (a.path, i, len(a.data), a.content_type, a.etag.replace('"', '\\"')))
    out.append("};")
    out.append("const uint32_t kWebAssetCount = %d;" % len(assets))
    out.append("")
    return "\n".join(out)


def generate(web_dir: Path, out_dir: Path) -> list[Asset]:
    assets = collect_assets(Path(web_dir))
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "web_assets.h").write_text(render_header(), encoding=SOURCE_ENCODING)
    (out_dir / "web_assets.cpp").write_text(render_source(assets), encoding=SOURCE_ENCODING)
    return assets


WEB_SUBDIR = "Software/src/devboard/webserver/web"
OUT_SUBDIR = "Software/src/devboard/webserver/generated"


def _main(project_root: Path, quiet: bool) -> None:
    try:
        assets = generate(project_root / WEB_SUBDIR, project_root / OUT_SUBDIR)
    except FileNotFoundError as exc:
        raise SystemExit("gen_web_assets: %s" % exc)
    if not quiet:
        for a in assets:
            print("%-24s %6d B raw -> %6d B gzip" % (a.path, a.raw_len, len(a.data)))


# PlatformIO runs this through SCons, whose namespace exports Import but has no
# __file__; standalone and under unittest it is the other way round.
if "Import" in globals():
    Import("env")  # noqa: F821
    _main(Path(env["PROJECT_DIR"]), quiet=True)  # noqa: F821
elif __name__ == "__main__":
    _main(Path(__file__).parent.parent, quiet=False)
